##
##      To build the AI_FACEFUSION_ docker image
##

# base stuff (from python 311)
FROM yeepeekoo/public:ai_base_cuda_python311


## face fusion requirements
RUN pip3 install \
    gradio \
    gfpgan \
    av \
    safetensors \
    realesrgan==0.3.0 

RUN pip3 install \
    numpy==1.23.4 \
    face_alignment==1.3.5 \
    imageio==2.19.3 \
    imageio-ffmpeg==0.4.7 

RUN pip3 install \
    numba \
    resampy==0.3.1 \
    pydub==0.25.1  \
    kornia==0.6.8 
    
RUN pip3 install \
    tqdm \
    yacs==0.1.8 \
    pyyaml  \
    joblib==1.1.0 
    
RUN pip3 install \
    basicsr==1.4.2 \
    facexlib==0.3.0

RUN pip3 install \
    insightface==0.7.3 \
    onnx==1.14.1 \
    onnxruntime==1.16.0 \
    onnxruntime-gpu==1.16.0 \
    opennsfw2==0.10.2 \
    psutil==5.9.5 

# run as a server
CMD ["uvicorn", "main_fastapi:app", "--host", "0.0.0.0", "--port", "5000"]
