##
##      To build the AI_FACEFUSION docker image
##

# base stuff
FROM yeepeekoo/public:ai_facefusion_


###### update latest OSAIS config (not an absolute requirement) ######

# push again the base files
COPY ./_static/* ./_static
COPY ./_templates/* ./_templates
COPY ./_osais/* .

# copy warmup files
COPY ./_input/warmup.jpg ./_input/warmup.jpg


###### specific AI config (must do) ######

# keep ai in its directory (this includes config files)
COPY ./ai/facefusion ./ai/facefusion
COPY ./ai/runai.py ./ai/runai.py

## warmup files
COPY ./_input/warmup.jpg ./_input/warmup.jpg
COPY ./_input/warmup.mp4 ./_input/warmup.mp4

# overload config with those default settings
ENV ENGINE=facefusion

# run as a server
CMD ["uvicorn", "main_fastapi:app", "--host", "0.0.0.0", "--port", "5311"]
